//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace $safeprojectname$.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("$safeprojectname$.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        internal static string cultures {
            get {
                return ResourceManager.GetString("cultures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestLogDir.
        /// </summary>
        internal static string CurrentUnitTestLogDirValue {
            get {
                return ResourceManager.GetString("CurrentUnitTestLogDirValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to testhost.
        /// </summary>
        internal static string ExpectedAppNameValue {
            get {
                return ResourceManager.GetString("ExpectedAppNameValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        internal static string ExpectedBoolValueNameValue {
            get {
                return ResourceManager.GetString("ExpectedBoolValueNameValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.Extensions.Logging.LoggerFactory.
        /// </summary>
        internal static string ExpectedFactoryValue {
            get {
                return ResourceManager.GetString("ExpectedFactoryValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $safeprojectname$.FileLogger.
        /// </summary>
        internal static string ExpectedILoggerValue {
            get {
                return ResourceManager.GetString("ExpectedILoggerValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string ExpectedIntValueNameValue {
            get {
                return ResourceManager.GetString("ExpectedIntValueNameValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/WMIConfig/2002/State.
        /// </summary>
        internal static string httpSchemasMicrosoftComWMIConfig2002State {
            get {
                return ResourceManager.GetString("httpSchemasMicrosoftComWMIConfig2002State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogDebugMessage Returned.
        /// </summary>
        internal static string UnitTestLogDebugMessage {
            get {
                return ResourceManager.GetString("UnitTestLogDebugMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogErrorMessage Returned.
        /// </summary>
        internal static string UnitTestLogErrorMessage {
            get {
                return ResourceManager.GetString("UnitTestLogErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WPFTestProjectLog.
        /// </summary>
        internal static string UnitTestLogFileName {
            get {
                return ResourceManager.GetString("UnitTestLogFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WPFTestProjectLogFileTest.
        /// </summary>
        internal static string UnitTestLogFileNameTest {
            get {
                return ResourceManager.GetString("UnitTestLogFileNameTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogInformationMessage Returned.
        /// </summary>
        internal static string UnitTestLogInformationMessage {
            get {
                return ResourceManager.GetString("UnitTestLogInformationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogMessage Returned.
        /// </summary>
        internal static string UnitTestLogMessage {
            get {
                return ResourceManager.GetString("UnitTestLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogTraceMessage Returned.
        /// </summary>
        internal static string UnitTestLogTraceMessage {
            get {
                return ResourceManager.GetString("UnitTestLogTraceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogWarningMessage Returned.
        /// </summary>
        internal static string UnitTestLogWarningMessage {
            get {
                return ResourceManager.GetString("UnitTestLogWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnitTestZipFile.zip.
        /// </summary>
        internal static string UnitTestZipFile {
            get {
                return ResourceManager.GetString("UnitTestZipFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimal.
        /// </summary>
        internal static string UnitTestZipFileCompressionLevel {
            get {
                return ResourceManager.GetString("UnitTestZipFileCompressionLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SampleDirectory.
        /// </summary>
        internal static string UnitTestZipFileFromDirectory {
            get {
                return ResourceManager.GetString("UnitTestZipFileFromDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.docx.
        /// </summary>
        internal static string UnitTestZipFileFromDirectoryFileExist {
            get {
                return ResourceManager.GetString("UnitTestZipFileFromDirectoryFileExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Readme.txt file is created during the Zip Process and added to the zip file.,Information about this package.,Line 2.,Line 3.,Line 4.,========================.
        /// </summary>
        internal static string UnitTestZipFileLinesToAddToNewFile {
            get {
                return ResourceManager.GetString("UnitTestZipFileLinesToAddToNewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Readme.txt.
        /// </summary>
        internal static string UnitTestZipFileNameToCreate {
            get {
                return ResourceManager.GetString("UnitTestZipFileNameToCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Readme.txt.
        /// </summary>
        internal static string UnitTestZipFileNameToDelete {
            get {
                return ResourceManager.GetString("UnitTestZipFileNameToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewReadme.txt.
        /// </summary>
        internal static string UnitTestZipFileToAddFullName {
            get {
                return ResourceManager.GetString("UnitTestZipFileToAddFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to urn:schemas-microsoft-com:unattend.
        /// </summary>
        internal static string urnSchemasMicrosoftComUnattend {
            get {
                return ResourceManager.GetString("urnSchemasMicrosoftComUnattend", resourceCulture);
            }
        }
    }
}
