// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace WPFAppWithDocFxLoggingZipAndTest
{
    internal sealed partial class Vsix
    {
        public const string Id = "WPFAppWithDocFxLoggingZipAndTest.93b6342c-0c8f-4c50-87e6-f0f96cad23b1";
        public const string Name = "WPFAppWithDocFxLoggingZipAndTest";
        public const string Description = @"Microsoft Test app for WPFAppWithDocFxLoggingZip Template under Visual Studio 2022.";
        public const string Language = "en-US";
        public const string Version = "8.0";
        public const string Author = "Danny McNaught";
        public const string Tags = "WPF; CSharp; Test; Zip; Logging";
    }
}
