// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace WPFAppWithDocFxLoggingZipAndTest
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string WPFAppWithDocFxLoggingZipAndTestString = "14810e86-b1dd-43c2-9c99-645288529d50";
        public static Guid WPFAppWithDocFxLoggingZipAndTest = new Guid(WPFAppWithDocFxLoggingZipAndTestString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {

    }
}